version: "3"

services:
  redis:
    image: redis:buster

  web1:
    build:
      context: ./web/
    ports:
      - "8000:8000"
    links:
      - redis

  web2:
    build:
      context: ./web/
    ports:
      - "8001:8000"
    links:
      - redis

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    links:
      - web1
      - web2
